language: node_js
node_js:
  - 12
os:
  - linux
  - windows
# This (filter_secrets) is generally unsafe, but we only run builds for master,
# so it is acceptable. If we remove the branch restriction, remove this too.
# If Windows builds on Travis are fixed, and work when secrets are in use,
# remove this too.
filter_secrets: false
matrix:
  include:
  - os: osx
    osx_image: xcode11.3
  allow_failures:
    - os: windows
env:
  - YARN_GPG=no
if: branch = development OR branch = master OR tag IS present
dist: xenial
addons:
  apt:
    packages:
      - libudev-dev
cache: yarn
before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ] || [ "$TRAVIS_OS_NAME" = "linux" ]; then unset CSC_KEY_PASSWORD CSC_LINK; fi
install:
  - yarn install --network-timeout 1000000
script:
  - yarn run build:$TRAVIS_OS_NAME
after_script:
  - yarn add --dev aws-sdk
  - tools/s3-upload.js
