import { BrowserWindow, screen } from "electron";
import log from "electron-log/main";
import LensOverlay from "../../main/managers/LensOverlay";
import Window from "../../main/managers/Window";
import type { KeyboardModel, LensSettings, LensState } from "../shared/types";
import { getLensSettings, getOverlayBounds, setOverlayBounds } from "./lens-settings";

// Magic constants auto-generated by Forge's Webpack plugin for the lens_window
// renderer entry point (dev-server URL in development, file:// path when packaged).
declare const LENS_WINDOW_WEBPACK_ENTRY: string;
declare const LENS_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

let overlayVisible = false;
let overlayStyleApplied = false;
let normalBounds: Electron.Rectangle | null = null;
let overlayBounds: Electron.Rectangle | null = null;
// The full intended bounds while overlay mode is active — our own source of
// truth for move/resize math (see overlayMove/overlayResize/guardOverlayBounds
// below), never read back from win.getBounds() mid-gesture: DWM rounds
// transparent/frameless window rects on Windows, and since resize deltas are
// small per-frame increments applied on top of the previous step, trusting a
// drifted read-back compounds that error every frame — most visibly on
// n/w-side resizes, where the drift shows up as position jitter (an e/s-only
// resize never touches x/y, so the same drift there is invisible).
let overlayLockedBounds: Electron.Rectangle | null = null;
let fixingOverlayBounds = false;

function getWin(): BrowserWindow | null {
  return LensOverlay.getWindow();
}

// ── Overlay bounds persistence ────────────────────────────────────────────────
// The overlay's position/size live in `overlayBounds` only for the session; on
// app restart they'd reset to the centered default. Persist them (debounced on
// move/resize, immediately on close) and restore on the next enable — but only
// if the saved rect is still visible on a currently attached display.

let persistBoundsTimer: ReturnType<typeof setTimeout> | null = null;

function persistOverlayBounds(): void {
  if (overlayBounds) setOverlayBounds(overlayBounds);
}

function schedulePersistBounds(): void {
  const win = getWin();
  if (!win || !overlayStyleApplied) return;
  overlayBounds = win.getBounds();
  if (persistBoundsTimer) clearTimeout(persistBoundsTimer);
  persistBoundsTimer = setTimeout(() => {
    persistBoundsTimer = null;
    persistOverlayBounds();
  }, 500);
}

// Width/height ratio of each product's SVG viewBox in the overlay renderer
// (src/lens/renderer/geometry-*.ts — keep these in sync if those ever change).
// The SVG scales at width:100% with no fixed height, so the browser's default
// preserveAspectRatio ("xMidYMid meet") fits it to the window without
// distorting it — but if the window itself isn't in the same ratio, that
// leaves blank (transparent, still-draggable) bars in the window around the
// actual keyboard image. Locking the window to the right ratio makes the
// image fill it exactly, so there's no dead space to grab.
const KEYBOARD_ASPECT_RATIO: Record<string, number> = {
  sonsei: 1270 / 462,
  defy: 1270 / 515,
  raise2: 1222 / 430,
};
const DEFAULT_ASPECT_RATIO = KEYBOARD_ASPECT_RATIO.sonsei;

/** Locks the window to the active keyboard's aspect ratio and, while the
 * overlay is showing, immediately corrects its current height to match
 * (setAspectRatio alone only constrains future resizes, it doesn't retroactively
 * fix a size that's already off-ratio). Call whenever the active model/product
 * changes. */
export function applyAspectRatioFor(product: string | null | undefined): void {
  const win = getWin();
  if (!win) return;
  const ratio = (product && KEYBOARD_ASPECT_RATIO[product.toLowerCase()]) || DEFAULT_ASPECT_RATIO;
  win.setAspectRatio(ratio);
  if (!overlayStyleApplied) return;
  const base = overlayLockedBounds ?? win.getBounds();
  const targetHeight = Math.round(base.width / ratio);
  if (targetHeight === base.height) return;
  const next = { x: base.x, y: base.y, width: base.width, height: targetHeight };
  if (overlayLockedBounds) overlayLockedBounds = next;
  win.setBounds(next);
  schedulePersistBounds();
}

function restoreOverlayBounds(): void {
  if (overlayBounds) return; // session bounds take priority over the stored ones
  const saved = getOverlayBounds();
  if (!saved) return;
  // Only restore if a meaningful part of the window is on some display, so a
  // monitor that's gone since last session can't strand the overlay off-screen.
  const visible = screen.getAllDisplays().some(d => {
    const a = d.workArea;
    const overlapX = Math.min(saved.x + saved.width, a.x + a.width) - Math.max(saved.x, a.x);
    const overlapY = Math.min(saved.y + saved.height, a.y + a.height) - Math.max(saved.y, a.y);
    return overlapX > 100 && overlapY > 60;
  });
  if (visible) {
    overlayBounds = saved;
  } else {
    log.info("[Lens] Saved overlay bounds are off-screen, ignoring");
  }
}

export function overlayAlive(): boolean {
  const win = getWin();
  return win !== null && !win.isDestroyed();
}

export function isOverlayVisible(): boolean {
  return overlayVisible;
}

// Corrects the window back to overlayLockedBounds if it drifts from it (e.g.
// DWM rounding). Must correct the FULL rect (x/y/width/height) together, not
// just size: win.setSize() alone re-anchors to the window's current top-left,
// which silently overrides the position half of an in-progress n/w-side
// resize — that fight between "resize sets x and width" and "guard resets
// only width, implicitly freezing x" is what produced the jitter.
function guardOverlayBounds(): void {
  const win = getWin();
  if (!win || !overlayLockedBounds || fixingOverlayBounds) return;
  const b = win.getBounds();
  const target = overlayLockedBounds;
  if (b.x !== target.x || b.y !== target.y || b.width !== target.width || b.height !== target.height) {
    fixingOverlayBounds = true;
    win.setBounds(target);
    setImmediate(() => {
      fixingOverlayBounds = false;
    });
  }
}

function preventOverlayResize(e: { preventDefault(): void }): void {
  e.preventDefault();
}

export function applyOverlayMode(enabled: boolean): void {
  const win = getWin();
  if (!win) return;
  const settings = getLensSettings();
  overlayStyleApplied = enabled;
  if (enabled) {
    normalBounds = win.getBounds();
    overlayLockedBounds = { ...(overlayBounds ?? normalBounds) };
    win.setOpacity(settings.opacity);
    // macOS: follow the user to whatever Space/full-screen app they're on, so
    // showing the overlay never switches Spaces. Joining a full-screen Space as
    // an auxiliary window only works while the window itself is not
    // fullscreenable, and the window level must be raised after the collection
    // behavior is set. skipTransformProcessType keeps the Dock icon stable.
    if (process.platform === "darwin") {
      win.setFullScreenable(false);
      win.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true, skipTransformProcessType: true });
    }
    win.setAlwaysOnTop(true, "screen-saver");
    // Resize Mode wanting mouse events means the window can't be click-through.
    win.setIgnoreMouseEvents(!settings.resizeMode, { forward: true });
    win.setResizable(false);
    win.removeListener("will-resize", preventOverlayResize);
    win.removeListener("resize", guardOverlayBounds);
    win.on("will-resize", preventOverlayResize);
    win.on("resize", guardOverlayBounds);
    win.webContents
      .executeJavaScript(
        `document.body.classList.add('overlay');${
          settings.resizeMode ? `document.body.classList.add('resize-mode');` : `document.body.classList.remove('resize-mode');`
        }`,
      )
      .catch(() => {});
    if (overlayBounds) win.setBounds(overlayBounds);
  } else {
    overlayLockedBounds = null;
    win.removeListener("will-resize", preventOverlayResize);
    win.removeListener("resize", guardOverlayBounds);
    overlayBounds = win.getBounds();
    persistOverlayBounds();
    win.setOpacity(1.0);
    win.setAlwaysOnTop(false);
    if (process.platform === "darwin") {
      win.setVisibleOnAllWorkspaces(false, { skipTransformProcessType: true });
    }
    win.setIgnoreMouseEvents(false);
    win.setResizable(true);
    win.webContents.executeJavaScript(`document.body.classList.remove('overlay','resize-mode');`).catch(() => {});
    if (normalBounds) win.setBounds(normalBounds);
  }
}

const FADE_IN_DURATION_MS = 80;
const FADE_OUT_DURATION_MS = 150;
const FADE_INTERVAL_MS = 16;
let fadeTimer: ReturnType<typeof setInterval> | null = null;
let fadeDelayTimer: ReturnType<typeof setTimeout> | null = null;

export function stopFade(): void {
  if (fadeTimer) {
    clearInterval(fadeTimer);
    fadeTimer = null;
  }
  if (fadeDelayTimer) {
    clearTimeout(fadeDelayTimer);
    fadeDelayTimer = null;
  }
}

// The window is never destroyed while hidden — its content stays fully rendered — so a
// plain win.show()/hide() reveals the finished layout instantly and only then plays
// Windows' own native reveal animation, producing a flash-then-animate glitch. Driving
// opacity ourselves in small steps gives one smooth, consistent transition instead.
function fadeWindowOpacity(target: number, duration: number, onComplete?: () => void): void {
  const win = getWin();
  if (!win) return;
  stopFade();
  const start = win.getOpacity();
  const startTime = Date.now();
  fadeTimer = setInterval(() => {
    const w = getWin();
    if (!w) {
      stopFade();
      return;
    }
    const t = Math.min(1, (Date.now() - startTime) / duration);
    w.setOpacity(start + (target - start) * t);
    if (t >= 1) {
      stopFade();
      onComplete?.();
    }
  }, FADE_INTERVAL_MS);
}

/**
 * `showOnStart` is the restored visibility from last session (see
 * getLastOverlayShown): the window is always created and its overlay styling
 * always applied, but it only actually goes on screen when the user left it
 * there — Lens must not pop up again after being hidden.
 */
export function createOverlayWindow(onReady: () => void, showOnStart: boolean): BrowserWindow {
  // Adopt last session's saved bounds (if still on-screen) so applyOverlayMode(true)
  // on ready-to-show places the overlay where the user left it.
  restoreOverlayBounds();
  const { width, height } = screen.getPrimaryDisplay().workAreaSize;

  const w = new BrowserWindow({
    width: Math.min(1270, width),
    height: Math.min(560, height),
    show: false,
    frame: false,
    transparent: true,
    backgroundColor: "#00000000",
    alwaysOnTop: false,
    skipTaskbar: true,
    // Required on macOS for visibleOnFullScreen (fullScreenAuxiliary) to stick.
    fullscreenable: false,
    // macOS: a non-activating NSPanel is the only window kind that can float
    // over other apps' full-screen Spaces without transforming the process to
    // UIElement (which would hide Bazecor's Dock icon).
    ...(process.platform === "darwin" ? { type: "panel" as const } : {}),
    webPreferences: {
      preload: LENS_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
      backgroundThrottling: false,
    },
  });

  LensOverlay.setWindow(w);
  w.loadURL(LENS_WINDOW_WEBPACK_ENTRY);

  w.once("ready-to-show", () => {
    log.info(`[Lens] Overlay window ready-to-show (showOnStart=${showOnStart})`);
    overlayVisible = showOnStart;
    applyOverlayMode(true);
    // showInactive: an overlay must never activate Bazecor — on macOS a plain
    // show() focuses the app, yanking the user out of whatever they're doing.
    if (showOnStart) w.showInactive();
    onReady();
  });

  w.webContents.setVisualZoomLevelLimits(1, 1);

  // Fires on app quit (and any other path that closes the window without going
  // through destroyOverlayWindow(), which persists explicitly before destroy()).
  // destroy() itself never emits "close", so the two paths don't double-save.
  w.on("close", () => {
    if (overlayStyleApplied) {
      overlayBounds = w.getBounds();
      persistOverlayBounds();
    }
  });

  w.on("closed", () => {
    LensOverlay.setWindow(null);
    overlayVisible = false;
    overlayStyleApplied = false;
  });

  return w;
}

export function destroyOverlayWindow(): void {
  stopFade();
  if (persistBoundsTimer) {
    clearTimeout(persistBoundsTimer);
    persistBoundsTimer = null;
  }
  const win = getWin();
  if (win && !win.isDestroyed()) {
    // Remember position/size for the next enable (and persist for the next session).
    if (overlayStyleApplied) {
      overlayBounds = win.getBounds();
      persistOverlayBounds();
    }
    win.destroy();
  }
  LensOverlay.setWindow(null);
  overlayVisible = false;
  overlayStyleApplied = false;
  overlayLockedBounds = null;
}

/**
 * `fadeDelayMs` holds the window on screen at zero opacity for that long before
 * the fade-in starts. A hidden window's renderer has no live compositor and
 * produces no frames, so anything pushed to it while hidden (most importantly a
 * new active layer) does not actually repaint until the window is back on
 * screen — fading in straight away plays the first frames of the reveal on
 * stale content, which then visibly swaps mid-fade. Presenting it fully
 * transparent first gives the renderer somewhere to repaint, invisibly, and the
 * fade then reveals content that is already correct. Callers that aren't
 * changing the content (Lens key TAP/HOLD, session restore) leave it at 0.
 */
export function showOverlay(fadeDelayMs = 0): void {
  const win = getWin();
  if (!win) return;
  overlayVisible = true;
  const settings = getLensSettings();
  // Only (re)apply overlay styling (bounds/opacity/always-on-top/CSS) once; hideOverlay()
  // never tears it down, so reapplying it on every show causes a visible flash.
  if (settings.overlayMode && !overlayStyleApplied) applyOverlayMode(true);
  const target = overlayStyleApplied ? settings.opacity : 1.0;
  stopFade();
  win.setOpacity(0);
  if (overlayStyleApplied) win.showInactive();
  else win.show();
  if (fadeDelayMs <= 0) {
    fadeWindowOpacity(target, FADE_IN_DURATION_MS);
    return;
  }
  fadeDelayTimer = setTimeout(() => {
    fadeDelayTimer = null;
    // hideOverlay() may have won the race while we waited (its own fade calls
    // stopFade(), but re-check rather than fade a window on its way out).
    if (!getWin() || !overlayVisible) return;
    fadeWindowOpacity(target, FADE_IN_DURATION_MS);
  }, fadeDelayMs);
}

export function hideOverlay(): void {
  const win = getWin();
  if (!win) return;
  overlayVisible = false;
  fadeWindowOpacity(0, FADE_OUT_DURATION_MS, () => {
    getWin()?.hide();
  });
}

export function applyOpacityLive(v: number): void {
  if (overlayStyleApplied) getWin()?.setOpacity(v);
}

/** Resize Mode makes the overlay's resize/move surface active, so it stops
 * being click-through. Toggled from the tray or Settings — both call this
 * same function so they can never drift out of sync. */
export function applyResizeModeLive(v: boolean): void {
  const win = getWin();
  if (!win || !overlayStyleApplied) return;
  win.setIgnoreMouseEvents(!v, { forward: true });
  win.webContents
    .executeJavaScript(v ? `document.body.classList.add('resize-mode');` : `document.body.classList.remove('resize-mode');`)
    .catch(() => {});
}

// ── Overlay drag / resize (driven by the overlay renderer in Resize Mode) ─────

export function overlayMove(x: number, y: number): void {
  const win = getWin();
  if (!win) return;
  // Absolute positioning: the renderer computes the target top-left from the
  // cursor's screen position minus the grab offset, so it self-corrects every
  // frame and never accumulates. Pin the size to the locked overlay size (our
  // own bookkeeping, not a fresh getBounds() read — see overlayLockedBounds)
  // so a move can never resize.
  const base = overlayLockedBounds ?? win.getBounds();
  const next = { x: Math.round(x), y: Math.round(y), width: base.width, height: base.height };
  if (overlayLockedBounds) overlayLockedBounds = next;
  win.setBounds(next);
  schedulePersistBounds();
}

export function overlayMoveBy(dx: number, dy: number): void {
  const win = getWin();
  if (!win) return;
  // Same reasoning as overlayResize below: build on our own last-known bounds,
  // not a fresh (potentially DWM-rounded) read-back, so per-frame deltas can't
  // compound into drift.
  const base = overlayLockedBounds ?? win.getBounds();
  const next = { x: base.x + Math.round(dx), y: base.y + Math.round(dy), width: base.width, height: base.height };
  if (overlayLockedBounds) overlayLockedBounds = next;
  win.setBounds(next);
  schedulePersistBounds();
}

export function overlayResize(dir: string, dx: number, dy: number): void {
  const win = getWin();
  if (!win) return;
  // dx/dy are small per-frame deltas (see App.tsx's ResizeFrame), applied on
  // top of the PREVIOUS step's result — so that base must be our own trusted
  // overlayLockedBounds, never a fresh win.getBounds()/getPosition() read.
  // Reading back drifts under DWM's rounding on transparent/frameless windows,
  // and unlike a move (position-only), a resize from the n/w edges changes x/y
  // *and* w/h together, so that per-step drift showed up as the window visibly
  // jittering/repositioning itself — invisible on a pure se resize, which
  // never touches x/y.
  const base = overlayLockedBounds ?? win.getBounds();
  let nx = base.x;
  let ny = base.y;
  let nw = base.width;
  let nh = base.height;
  if (dir.includes("e")) nw = Math.max(400, base.width + dx);
  if (dir.includes("s")) nh = Math.max(200, base.height + dy);
  if (dir.includes("w")) {
    nx = base.x + dx;
    nw = Math.max(400, base.width - dx);
  }
  if (dir.includes("n")) {
    ny = base.y + dy;
    nh = Math.max(200, base.height - dy);
  }
  const next = { x: Math.round(nx), y: Math.round(ny), width: Math.round(nw), height: Math.round(nh) };
  if (overlayLockedBounds) overlayLockedBounds = next;
  win.setBounds(next);
  schedulePersistBounds();
}

// ── Push helpers (main → overlay renderer) ────────────────────────────────────

export function pushModel(model: KeyboardModel): void {
  if (overlayAlive()) getWin()!.webContents.send("lens:model", model);
}

export function pushActiveLayer(layer: number): void {
  if (overlayAlive()) getWin()!.webContents.send("lens:active-layer", layer);
}

export function pushState(state: LensState): void {
  if (overlayAlive()) getWin()!.webContents.send("lens:state", state);
}

/** Sends state to the overlay AND the main Bazecor window (used for changes the
 * settings UI must react to, e.g. the macOS Input Monitoring permission banner). */
export function broadcastState(state: LensState): void {
  pushState(state);
  const main = Window.getWindow();
  if (main && !main.isDestroyed()) main.webContents.send("lens:state", state);
}

/** Sends settings to the overlay AND the main Bazecor window so both UIs stay in sync. */
export function broadcastSettings(settings: LensSettings): void {
  if (overlayAlive()) getWin()!.webContents.send("lens:settings", settings);
  const main = Window.getWindow();
  if (main && !main.isDestroyed()) main.webContents.send("lens:settings", settings);
}
