import { app, BrowserWindow } from "electron";
import windowStateKeeper from "electron-window-state";
import path from "path";
import { configureNativeTheme } from "./setup/theme";
import { configureIPCs } from "./setup/configureIPCs";
import configureRedirect from "./setup/configureRedirect";
import onDevTools from "./setup/onDevTools";
import onReadyToShow from "./setup/onReadyToShow";
import onClose from "./setup/onClose";
import Window from "./managers/Window";
import { configureUSB } from "./setup/configureUSB";
import { configureHID, removeHIDListeners } from "./setup/configureHID";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

const createWindow = () => {
  // Undoes the accessory-app switch onClose.ts makes in background mode: with a
  // real window on screen again Bazecor belongs in the Dock (and needs to be
  // able to take focus) rather than living in the tray alone.
  if (process.platform === "darwin" && !app.dock?.isVisible()) {
    app.dock?.show();
  }

  // Create the browser window.
  const mainWindowState = windowStateKeeper({
    defaultWidth: 1200,
    defaultHeight: 900,
  });

  const mainWindow = new BrowserWindow({
    x: mainWindowState.x,
    y: mainWindowState.y,
    width: mainWindowState.width,
    height: mainWindowState.height,
    minWidth: 650,
    minHeight: 570,
    resizable: true,
    icon: path.join("../renderer/static", "/logo.png"),
    show: false,
    backgroundColor: "#2e2c29",
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      sandbox: false,
      nodeIntegration: true,
      contextIsolation: false,
      webSecurity: false,
      backgroundThrottling: false,
    },
  });

  mainWindow.on("close", () => {
    // Always let the window actually close (and free its renderer) here, even in
    // background mode: the Lens overlay lives in its own window and doesn't need
    // the configurator's renderer resident. onClose.ts decides whether that also
    // quits the whole app, based on background mode.
    removeHIDListeners();
  });

  mainWindow.webContents.on("did-finish-load", () => {
    // Open the DevTools when the content is fully loaded
    // mainWindow.webContents.openDevTools();
  });

  configureIPCs();
  mainWindowState.manage(mainWindow);

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  Window.getInstance(); // init Windows manager
  Window.setWindow(mainWindow);

  configureNativeTheme();
  configureRedirect();
  onReadyToShow();
  onDevTools();
  onClose();
  configureHID();
  configureUSB();
};

export default createWindow;
